FROM ubuntu:bionic

LABEL maintainer="Mrinal Sinha <mail@themrinalsinha.com>"

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    libmysqlclient-dev \
    python3-setuptools \
    python3-dev \
    python3-pip \
    curl \
    flake8 \
    git \
    sudo
